Update issue templates
redhat-developer/openshift-dd-ext pull request #74
Opened 2022-10-08 16:43 UTC by vatana7

- The PR for Issue #73

2022-10-10 18:44 UTC, dgolovin requested changes

2022-10-10 18:44 UTC, dgolovin commented on .github/ISSUE_TEMPLATE/bug-report-👾.md
> +labels: ''
please add 'bug' label

2022-10-10 18:44 UTC, dgolovin commented on .github/ISSUE_TEMPLATE/bug-report-👾.md
> +**Smartphone (please complete the following information):**
Please remove this section, because it is not applicable.

2022-10-10 18:44 UTC, dgolovin commented on .github/ISSUE_TEMPLATE/bug-report-👾.md
> + - Browser [e.g. chrome, safari]
Please remove this line, because it is not applicable.

2022-10-10 18:44 UTC, dgolovin commented on .github/ISSUE_TEMPLATE/feature-request-🤟🏻.md
> +labels: ''
Please add 'enhancement' label.

2022-10-10 18:44 UTC, dgolovin commented on .github/ISSUE_TEMPLATE/bug-report-👾.md
> +
Please add 

**Extension info**
- Version: [e.g. 0.0.1]

2022-10-11 04:15 UTC, vatana7 commented
I have made changes as you have requested. Please check ✌🏻

2022-10-11 06:08 UTC, dgolovin approved these changes
I updated labels for feature request and bug. LGTM :+1:

2022-10-11 06:13 UTC, merged

2022-10-11 06:52 UTC, vatana7 commented
Thanks!